/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function seq2ColNative(inputs: Float32Array, batchSize: number, sequenceLength: number, inputDim: number, kernelSize: number, strides: number, padLeft: number, out: Float32Array): void
export declare function col2SeqNative(gradOut: Float32Array, batchSize: number, sequenceLength: number, inputDim: number, kernelSize: number, strides: number, padLeft: number, gradIn: Float32Array): void
export declare function grid2ColNative(inputs: Float32Array, batchSize: number, height: number, width: number, channels: number, kernelRows: number, kernelCols: number, strideRows: number, strideCols: number, padTop: number, padLeft: number, hOut: number, wOut: number, out: Float32Array): void
export declare function col2GridNative(gradOut: Float32Array, batchSize: number, height: number, width: number, channels: number, kernelRows: number, kernelCols: number, strideRows: number, strideCols: number, padTop: number, padLeft: number, hOut: number, wOut: number, gradIn: Float32Array): void
export declare function maxPooling1DForwardNative(inputs: Float32Array, batchSize: number, sequenceLength: number, inputDim: number, poolSize: number, strides: number, padLeft: number, out: Float32Array, maxIndices: Int32Array): void
export declare function maxPooling1DBackwardNative(gradOut: Float32Array, maxIndices: Int32Array, gradIn: Float32Array): void
export declare function maxPooling2DForwardNative(inputs: Float32Array, batchSize: number, height: number, width: number, channels: number, poolRows: number, poolCols: number, strideRows: number, strideCols: number, padTop: number, padLeft: number, hOut: number, wOut: number, out: Float32Array, maxIndices: Int32Array): void
export declare function maxPooling2DBackwardNative(gradOut: Float32Array, maxIndices: Int32Array, gradIn: Float32Array): void
export declare function averagePooling1DForwardNative(inputs: Float32Array, batchSize: number, sequenceLength: number, inputDim: number, poolSize: number, strides: number, padLeft: number, out: Float32Array, windowCounts: Int32Array): void
export declare function averagePooling1DBackwardNative(gradOut: Float32Array, windowCounts: Int32Array, batchSize: number, sequenceLength: number, inputDim: number, poolSize: number, strides: number, padLeft: number, gradIn: Float32Array): void
export declare function averagePooling2DForwardNative(inputs: Float32Array, batchSize: number, height: number, width: number, channels: number, poolRows: number, poolCols: number, strideRows: number, strideCols: number, padTop: number, padLeft: number, hOut: number, wOut: number, out: Float32Array, windowCounts: Int32Array): void
export declare function averagePooling2DBackwardNative(gradOut: Float32Array, windowCounts: Int32Array, batchSize: number, height: number, width: number, channels: number, poolRows: number, poolCols: number, strideRows: number, strideCols: number, padTop: number, padLeft: number, hOut: number, wOut: number, gradIn: Float32Array): void
export declare function embeddingForwardNative(inputs: Float32Array, embeddings: Float32Array, vocabSize: number, embeddingDim: number, out: Float32Array): void
export declare function embeddingBackwardNative(gradOut: Float32Array, inputs: Float32Array, vocabSize: number, embeddingDim: number, gradEmbed: Float32Array): void
export declare function layerNormalizationForwardNative(inputs: Float32Array, gamma: Float32Array, beta: Float32Array, epsilon: number, out: Float32Array, mean: Float32Array, invStd: Float32Array): void
export declare function layerNormalizationBackwardNative(gradOut: Float32Array, inputs: Float32Array, mean: Float32Array, invStd: Float32Array, gamma: Float32Array, gradIn: Float32Array, gradGamma: Float32Array, gradBeta: Float32Array): void
export declare function batchNormalizationForwardNative(inputs: Float32Array, gamma: Float32Array, beta: Float32Array, movingMean: Float32Array, movingVariance: Float32Array, epsilon: number, momentum: number, training: boolean, out: Float32Array, mean: Float32Array, invStd: Float32Array): void
export declare function batchNormalizationBackwardNative(gradOut: Float32Array, inputs: Float32Array, mean: Float32Array, invStd: Float32Array, gamma: Float32Array, training: boolean, gradIn: Float32Array, gradGamma: Float32Array, gradBeta: Float32Array): void
