/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'layers-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.android-arm64.node')
          } else {
            nativeBinding = require('@oxide-js/layers-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'layers-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@oxide-js/layers-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'layers-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@oxide-js/layers-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'layers-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@oxide-js/layers-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'layers-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@oxide-js/layers-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'layers-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./layers-native.darwin-universal.node')
      } else {
        nativeBinding = require('@oxide-js/layers-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'layers-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.darwin-x64.node')
          } else {
            nativeBinding = require('@oxide-js/layers-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'layers-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@oxide-js/layers-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'layers-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./layers-native.freebsd-x64.node')
      } else {
        nativeBinding = require('@oxide-js/layers-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'layers-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./layers-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@oxide-js/layers-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'layers-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./layers-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@oxide-js/layers-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { seq2ColNative, col2SeqNative, grid2ColNative, col2GridNative, maxPooling1DForwardNative, maxPooling1DBackwardNative, maxPooling2DForwardNative, maxPooling2DBackwardNative, averagePooling1DForwardNative, averagePooling1DBackwardNative, averagePooling2DForwardNative, averagePooling2DBackwardNative, embeddingForwardNative, embeddingBackwardNative, layerNormalizationForwardNative, layerNormalizationBackwardNative, batchNormalizationForwardNative, batchNormalizationBackwardNative, rnnForwardNative, rnnBackwardNative, lstmForwardNative, lstmBackwardNative, gruForwardNative, gruBackwardNative, attentionForwardNative, attentionBackwardNative, multiHeadAttentionForwardNative, multiHeadAttentionBackwardNative } = nativeBinding

module.exports.seq2ColNative = seq2ColNative
module.exports.col2SeqNative = col2SeqNative
module.exports.grid2ColNative = grid2ColNative
module.exports.col2GridNative = col2GridNative
module.exports.maxPooling1DForwardNative = maxPooling1DForwardNative
module.exports.maxPooling1DBackwardNative = maxPooling1DBackwardNative
module.exports.maxPooling2DForwardNative = maxPooling2DForwardNative
module.exports.maxPooling2DBackwardNative = maxPooling2DBackwardNative
module.exports.averagePooling1DForwardNative = averagePooling1DForwardNative
module.exports.averagePooling1DBackwardNative = averagePooling1DBackwardNative
module.exports.averagePooling2DForwardNative = averagePooling2DForwardNative
module.exports.averagePooling2DBackwardNative = averagePooling2DBackwardNative
module.exports.embeddingForwardNative = embeddingForwardNative
module.exports.embeddingBackwardNative = embeddingBackwardNative
module.exports.layerNormalizationForwardNative = layerNormalizationForwardNative
module.exports.layerNormalizationBackwardNative = layerNormalizationBackwardNative
module.exports.batchNormalizationForwardNative = batchNormalizationForwardNative
module.exports.batchNormalizationBackwardNative = batchNormalizationBackwardNative
module.exports.rnnForwardNative = rnnForwardNative
module.exports.rnnBackwardNative = rnnBackwardNative
module.exports.lstmForwardNative = lstmForwardNative
module.exports.lstmBackwardNative = lstmBackwardNative
module.exports.gruForwardNative = gruForwardNative
module.exports.gruBackwardNative = gruBackwardNative
module.exports.attentionForwardNative = attentionForwardNative
module.exports.attentionBackwardNative = attentionBackwardNative
module.exports.multiHeadAttentionForwardNative = multiHeadAttentionForwardNative
module.exports.multiHeadAttentionBackwardNative = multiHeadAttentionBackwardNative
