/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function dotProduct(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, transA: boolean, transB: boolean): Float32Array
export declare function dotProductInto(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function dotProductIntoDims(aData: Float32Array, aRows: number, aCols: number, bData: Float32Array, bRows: number, bCols: number, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function addMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function subMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function mulMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function divMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function softmaxNativeInto(data: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function softmaxBackwardNativeInto(sData: Float32Array, gData: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function layerNormNativeInto(xData: Float32Array, gamma: Float32Array, beta: Float32Array, rows: number, cols: number, eps: number, outRes: Float32Array, outNorm: Float32Array, outMeans: Float32Array, outStds: Float32Array): void
export declare function layerNormBackwardNativeInto(errData: Float32Array, normData: Float32Array, gammaData: Float32Array, rows: number, cols: number, stdData: Float32Array, dGammaOut: Float32Array, dBetaOut: Float32Array, dxOut: Float32Array): void
export declare function reluNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function sigmoidNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function tanhNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function embeddingForwardNativeInto(indices: Array<number>, weightData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId: number | undefined | null, out: Float32Array): void
export declare function embeddingBackwardNative(indices: Array<number>, errData: Float32Array, gradData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function convolutionNativeInto(aData: Float32Array, aRows: number, aCols: number, kData: Float32Array, kRows: number, kCols: number, out: Float32Array): void
export declare function convBackwardInputNativeInto(errData: Float32Array, errRows: number, errCols: number, inputData: Float32Array, inputRows: number, inputCols: number, outRows: number, outCols: number, out: Float32Array): void
export declare function applyAttentionMaskNative(data: Float32Array, padMask: Array<boolean>, rows: number, cols: number, scale: number): void
export declare function adamUpdateNative(grad: Float32Array, m: Float32Array, v: Float32Array, buffer: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number): void
export declare function addInPlace(a: Float32Array, b: Float32Array): void
export declare function subInPlace(a: Float32Array, b: Float32Array): void
export declare function mulInPlace(a: Float32Array, b: Float32Array): void
export declare function mseNative(yTrue: Float32Array, yPred: Float32Array): Array<number>
export declare function addBiasNative(data: Float32Array, bias: Float32Array, rows: number, cols: number): void
export declare function sumAxisNative(data: Float32Array, rows: number, cols: number, axis: number, out: Float32Array): void
export declare function clipGradientsNative(data: Float32Array, limit: number): void
export declare function multiHeadAttentionForwardNativeInto(qData: Float32Array, kData: Float32Array, vData: Float32Array, padMask: Array<boolean>, heads: number, headUnits: number, seqLen: number, batchSize: number, scale: number, outData: Float32Array, attentionData: Float32Array): void
export declare function multiHeadAttentionBackwardNativeInto(qData: Float32Array, kData: Float32Array, vData: Float32Array, attentionData: Float32Array, dOutData: Float32Array, padMask: Array<boolean>, heads: number, headUnits: number, seqLen: number, batchSize: number, scale: number, dQOut: Float32Array, dKOut: Float32Array, dVOut: Float32Array): void
