/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function lstmForwardNativeInto(wxi: Float32Array, wxf: Float32Array, wxo: Float32Array, wxg: Float32Array, whi: Float32Array, whf: Float32Array, who: Float32Array, whg: Float32Array, bi: Float32Array, bf: Float32Array, bo: Float32Array, bg: Float32Array, xSeq: Float32Array, h0: Float32Array, c0: Float32Array, hiddenUnits: number, inputUnits: number, seqLen: number, batchSize: number, hSeq: Float32Array, cSeq: Float32Array, giSeq: Float32Array, gfSeq: Float32Array, goSeq: Float32Array, ggSeq: Float32Array): void
export declare function rnnForwardNativeInto(wxh: Float32Array, whh: Float32Array, bias: Float32Array, xSeq: Float32Array, h0: Float32Array, hiddenUnits: number, inputUnits: number, seqLen: number, batchSize: number, hSeq: Float32Array, actGrad: Float32Array): void
export declare function rnnBackwardNativeInto(wxh: Float32Array, whh: Float32Array, xSeq: Float32Array, hSeq: Float32Array, dAct: Float32Array, errH: Float32Array, hiddenUnits: number, inputUnits: number, seqLen: number, batchSize: number, dwxh: Float32Array, dwhh: Float32Array, dbh: Float32Array, dxOut: Float32Array): void
export declare function gruForwardNativeInto(wxr: Float32Array, whr: Float32Array, br: Float32Array, wxz: Float32Array, whz: Float32Array, bz: Float32Array, wxh: Float32Array, whh: Float32Array, bh: Float32Array, xSeq: Float32Array, h0: Float32Array, hiddenUnits: number, inputUnits: number, seqLen: number, batchSize: number, hSeq: Float32Array, rSeq: Float32Array, zSeq: Float32Array, nSeq: Float32Array): void
export declare function gruBackwardNativeInto(wxr: Float32Array, whr: Float32Array, wxz: Float32Array, whz: Float32Array, wxh: Float32Array, whh: Float32Array, xSeq: Float32Array, hSeq: Float32Array, rSeq: Float32Array, zSeq: Float32Array, nSeq: Float32Array, errH: Float32Array, hiddenUnits: number, inputUnits: number, seqLen: number, batchSize: number, dwxr: Float32Array, dwhr: Float32Array, dbr: Float32Array, dwxz: Float32Array, dwhz: Float32Array, dbz: Float32Array, dwxh: Float32Array, dwhh: Float32Array, dbh: Float32Array, dxOut: Float32Array): void
export interface MaskedSparseSoftmaxCrossEntropyResult {
  loss: number
  validTokens: number
}
export interface EmbeddingSparseBackwardResult {
  uniqueIndices: Int32Array
  grad: Float32Array
}
export declare function dotProduct(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, transA: boolean, transB: boolean): Float32Array
export declare function dotProductInto(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function dotProductIntoDims(aData: Float32Array, aRows: number, aCols: number, bData: Float32Array, bRows: number, bCols: number, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function addMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function subMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function mulMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function divMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function softmaxNativeInto(data: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function softmaxBackwardNativeInto(sData: Float32Array, gData: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function layerNormNativeInto(xData: Float32Array, gamma: Float32Array, beta: Float32Array, rows: number, cols: number, eps: number, outRes: Float32Array, outNorm: Float32Array, outMeans: Float32Array, outStds: Float32Array): void
export declare function layerNormBackwardNativeInto(errData: Float32Array, normData: Float32Array, gammaData: Float32Array, rows: number, cols: number, stdData: Float32Array, dGammaOut: Float32Array, dBetaOut: Float32Array, dxOut: Float32Array): void
export declare function reluNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function sigmoidNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function tanhNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function embeddingForwardNativeInto(indices: Array<number>, weightData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId: number | undefined | null, out: Float32Array): void
export declare function embeddingForwardNativeInt32Into(indices: Int32Array, weightData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId: number | undefined | null, out: Float32Array): void
export declare function embeddingBackwardNative(indices: Array<number>, errData: Float32Array, gradData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingBackwardNativeInt32(indices: Int32Array, errData: Float32Array, gradData: Float32Array, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingBackwardSparseNative(indices: Int32Array, errData: Float32Array, embeddingDim: number, padTokenId?: number | undefined | null): EmbeddingSparseBackwardResult
/**
 * Fused Embedding backward + Adam update.
 *
 * Layout assumptions (same as existing code):
 *   weight / m / v  : flat [embeddingDim, vocabSize]  → index `i * vocabSize + tokenIndex`
 *   err_data        : flat [embeddingDim, seqLen]      → index `i * seqLen + j`
 *   indices.length  == seqLen
 *
 * The function does everything in one NAPI call:
 *   1) Build unique-token map
 *   2) Accumulate gradients per unique token
 *   3) Apply Adam update directly into `weight`, `m`, `v`
 *
 * Nothing is returned – no allocation crosses the JS boundary.
 */
export declare function embeddingAdamBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, m: Float32Array, v: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
/**
 * Fused Embedding backward + SGD update.
 *
 * update rule: weight[i * vocabSize + tokenIdx] -= alpha * grad
 *
 * Layout same as embedding_adam_backward_update_native.
 */
export declare function embeddingSgdBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, alpha: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
/**
 * Fused Embedding backward + AdaGrad update.
 *
 * update rule: sum += g²; weight -= alpha * g / sqrt(sum + eps)
 *
 * `sum_data` layout: flat [embeddingDim, vocabSize]
 */
export declare function embeddingAdagradBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, sumData: Float32Array, alpha: number, epsilon: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
/**
 * Fused Embedding backward + Momentum update.
 *
 * update rule: v = beta * v + alpha * g; weight -= v
 *
 * `v_data` layout: flat [embeddingDim, vocabSize] (velocity / prev gradient)
 */
export declare function embeddingMomentumBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, vData: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
/**
 * Fused Embedding backward + NAG (Nesterov Accelerated Gradient) update.
 *
 * update rule: v_new = beta * v_old + alpha * (g - beta * v_old); weight -= v_new
 *
 * `v_data` layout: flat [embeddingDim, vocabSize]
 */
export declare function embeddingNagBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, vData: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function convolutionNativeInto(aData: Float32Array, aRows: number, aCols: number, kData: Float32Array, kRows: number, kCols: number, out: Float32Array): void
export declare function convBackwardInputNativeInto(errData: Float32Array, errRows: number, errCols: number, inputData: Float32Array, inputRows: number, inputCols: number, outRows: number, outCols: number, out: Float32Array): void
export declare function applyAttentionMaskNative(data: Float32Array, padMask: Array<boolean>, rows: number, cols: number, scale: number): void
export declare function adamUpdateNative(grad: Float32Array, m: Float32Array, v: Float32Array, buffer: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number): void
export declare function adamSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, m: Float32Array, v: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number, vocabSize: number, embeddingDim: number): void
export declare function sgdUpdateNative(grad: Float32Array, out: Float32Array, alpha: number): void
export declare function sgdSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, alpha: number, vocabSize: number, embeddingDim: number): void
export declare function adagradUpdateNative(grad: Float32Array, sum: Float32Array, out: Float32Array, alpha: number, epsilon: number): void
export declare function adagradSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, sum: Float32Array, alpha: number, epsilon: number, vocabSize: number, embeddingDim: number): void
export declare function momentumUpdateNative(grad: Float32Array, v: Float32Array, out: Float32Array, alpha: number, beta: number): void
export declare function momentumSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, v: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number): void
export declare function nagUpdateNative(grad: Float32Array, v: Float32Array, out: Float32Array, alpha: number, beta: number): void
export declare function nagSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, v: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number): void
export declare function addInPlace(a: Float32Array, b: Float32Array): void
export declare function subInPlace(a: Float32Array, b: Float32Array): void
export declare function mulInPlace(a: Float32Array, b: Float32Array): void
export declare function mseNative(yTrue: Float32Array, yPred: Float32Array): Array<number>
export declare function addBiasNative(data: Float32Array, bias: Float32Array, rows: number, cols: number): void
export declare function sumAxisNative(data: Float32Array, rows: number, cols: number, axis: number, out: Float32Array): void
export declare function clipGradientsNative(data: Float32Array, limit: number): void
export declare function denseLinearBackwardNativeInto(errActivation: Float32Array, input: Float32Array, weight: Float32Array, outputUnits: number, units: number, seqLen: number, clipLimit: number, gradWeightOut: Float32Array, gradBiasOut: Float32Array, prevErrOut: Float32Array): void
export declare function maskedSparseSoftmaxCrossEntropyInto(logits: Float32Array, inputTokens: Float32Array, targets: Float32Array, seqLen: number, batchSize: number, vocabSize: number, padTokenId: number | undefined | null, outGrad: Float32Array): MaskedSparseSoftmaxCrossEntropyResult
export declare function projectLastTokenLogitsNativeInto(hidden: Float32Array, weight: Float32Array, bias: Float32Array, units: number, seqLen: number, batchSize: number, vocabSize: number, out: Float32Array): void
export declare function multiHeadAttentionForwardNativeInto(qData: Float32Array, kData: Float32Array, vData: Float32Array, padMask: Array<boolean>, heads: number, headUnits: number, seqLen: number, batchSize: number, scale: number, outData: Float32Array, attentionData: Float32Array): void
export declare function multiHeadAttentionBackwardNativeInto(qData: Float32Array, kData: Float32Array, vData: Float32Array, attentionData: Float32Array, dOutData: Float32Array, padMask: Array<boolean>, heads: number, headUnits: number, seqLen: number, batchSize: number, scale: number, dQOut: Float32Array, dKOut: Float32Array, dVOut: Float32Array): void
