/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'oxide-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.android-arm64.node')
          } else {
            nativeBinding = require('@oxide-js/core-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'oxide-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@oxide-js/core-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@oxide-js/core-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@oxide-js/core-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@oxide-js/core-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'oxide-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./oxide-native.darwin-universal.node')
      } else {
        nativeBinding = require('@oxide-js/core-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'oxide-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.darwin-x64.node')
          } else {
            nativeBinding = require('@oxide-js/core-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@oxide-js/core-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'oxide-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./oxide-native.freebsd-x64.node')
      } else {
        nativeBinding = require('@oxide-js/core-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@oxide-js/core-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@oxide-js/core-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { reluNativeInto, sigmoidNativeInto, tanhNativeInto, lReluNativeInto, convolutionNativeInto, softmaxNativeInto, softmaxBackwardNativeInto, mseNative, dotProduct, dotProductInto, dotProductIntoDims, addMatricesInto, subMatricesInto, mulMatricesInto, divMatricesInto, addInPlace, subInPlace, mulInPlace, addBiasNative, sumAxisNative, powNative, absmNative, expmNative, logmNative, transposeNative, adamUpdateNative, sgdUpdateNative, adagradUpdateNative, momentumUpdateNative, nagUpdateNative, clipGradientsNative } = nativeBinding

module.exports.reluNativeInto = reluNativeInto
module.exports.sigmoidNativeInto = sigmoidNativeInto
module.exports.tanhNativeInto = tanhNativeInto
module.exports.lReluNativeInto = lReluNativeInto
module.exports.convolutionNativeInto = convolutionNativeInto
module.exports.softmaxNativeInto = softmaxNativeInto
module.exports.softmaxBackwardNativeInto = softmaxBackwardNativeInto
module.exports.mseNative = mseNative
module.exports.dotProduct = dotProduct
module.exports.dotProductInto = dotProductInto
module.exports.dotProductIntoDims = dotProductIntoDims
module.exports.addMatricesInto = addMatricesInto
module.exports.subMatricesInto = subMatricesInto
module.exports.mulMatricesInto = mulMatricesInto
module.exports.divMatricesInto = divMatricesInto
module.exports.addInPlace = addInPlace
module.exports.subInPlace = subInPlace
module.exports.mulInPlace = mulInPlace
module.exports.addBiasNative = addBiasNative
module.exports.sumAxisNative = sumAxisNative
module.exports.powNative = powNative
module.exports.absmNative = absmNative
module.exports.expmNative = expmNative
module.exports.logmNative = logmNative
module.exports.transposeNative = transposeNative
module.exports.adamUpdateNative = adamUpdateNative
module.exports.sgdUpdateNative = sgdUpdateNative
module.exports.adagradUpdateNative = adagradUpdateNative
module.exports.momentumUpdateNative = momentumUpdateNative
module.exports.nagUpdateNative = nagUpdateNative
module.exports.clipGradientsNative = clipGradientsNative
