/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function reluNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function sigmoidNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function tanhNativeInto(input: Float32Array, outRes: Float32Array, outGrad: Float32Array): void
export declare function convolutionNativeInto(aData: Float32Array, aRows: number, aCols: number, kData: Float32Array, kRows: number, kCols: number, out: Float32Array): void
export declare function embeddingAdamBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, m: Float32Array, v: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingSgdBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, alpha: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingAdagradBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, sumData: Float32Array, alpha: number, epsilon: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingMomentumBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, vData: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function embeddingNagBackwardUpdateNative(indices: Int32Array, errData: Float32Array, weight: Float32Array, vData: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number, padTokenId?: number | undefined | null): void
export declare function softmaxNativeInto(data: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function softmaxBackwardNativeInto(sData: Float32Array, gData: Float32Array, rows: number, cols: number, isRow: boolean, out: Float32Array): void
export declare function mseNative(yTrue: Float32Array, yPred: Float32Array): Array<number>
export declare function dotProduct(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, transA: boolean, transB: boolean): Float32Array
export declare function dotProductInto(aData: Float32Array, aShape: Array<number>, bData: Float32Array, bShape: Array<number>, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function dotProductIntoDims(aData: Float32Array, aRows: number, aCols: number, bData: Float32Array, bRows: number, bCols: number, outData: Float32Array, transA: boolean, transB: boolean): void
export declare function addMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function subMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function mulMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function divMatricesInto(a: Float32Array, b: Float32Array, out: Float32Array): void
export declare function addInPlace(a: Float32Array, b: Float32Array): void
export declare function subInPlace(a: Float32Array, b: Float32Array): void
export declare function mulInPlace(a: Float32Array, b: Float32Array): void
export declare function addBiasNative(data: Float32Array, bias: Float32Array, rows: number, cols: number): void
export declare function sumAxisNative(data: Float32Array, rows: number, cols: number, axis: number, out: Float32Array): void
export declare function adamUpdateNative(grad: Float32Array, m: Float32Array, v: Float32Array, buffer: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number): void
export declare function adamSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, m: Float32Array, v: Float32Array, t: number, alpha: number, beta1: number, beta2: number, epsilon: number, vocabSize: number, embeddingDim: number): void
export declare function sgdUpdateNative(grad: Float32Array, out: Float32Array, alpha: number): void
export declare function sgdSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, alpha: number, vocabSize: number, embeddingDim: number): void
export declare function adagradUpdateNative(grad: Float32Array, sum: Float32Array, out: Float32Array, alpha: number, epsilon: number): void
export declare function adagradSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, sum: Float32Array, alpha: number, epsilon: number, vocabSize: number, embeddingDim: number): void
export declare function momentumUpdateNative(grad: Float32Array, v: Float32Array, out: Float32Array, alpha: number, beta: number): void
export declare function momentumSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, v: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number): void
export declare function nagUpdateNative(grad: Float32Array, v: Float32Array, out: Float32Array, alpha: number, beta: number): void
export declare function nagSparseUpdateNative(indices: Int32Array, grad: Float32Array, weight: Float32Array, v: Float32Array, alpha: number, beta: number, vocabSize: number, embeddingDim: number): void
export declare function clipGradientsNative(data: Float32Array, limit: number): void
