/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'oxide-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.android-arm64.node')
          } else {
            nativeBinding = require('@oxidejs/core-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'oxide-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('@oxidejs/core-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@oxidejs/core-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@oxidejs/core-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@oxidejs/core-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'oxide-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./oxide-native.darwin-universal.node')
      } else {
        nativeBinding = require('@oxidejs/core-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'oxide-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.darwin-x64.node')
          } else {
            nativeBinding = require('@oxidejs/core-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@oxidejs/core-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'oxide-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./oxide-native.freebsd-x64.node')
      } else {
        nativeBinding = require('@oxidejs/core-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxide-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxide-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@oxidejs/core-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'oxide-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxide-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@oxidejs/core-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { dotProduct, dotProductInto, dotProductIntoDims, addMatricesInto, subMatricesInto, mulMatricesInto, divMatricesInto, addInPlace, subInPlace, mulInPlace, addBiasNative, sumAxisNative, reluNativeInto, sigmoidNativeInto, tanhNativeInto, adamUpdateNative, adamSparseUpdateNative, sgdUpdateNative, sgdSparseUpdateNative, adagradUpdateNative, adagradSparseUpdateNative, momentumUpdateNative, momentumSparseUpdateNative, nagUpdateNative, nagSparseUpdateNative, mseNative, maskedSparseSoftmaxCrossEntropyInto, embeddingForwardNativeInto, embeddingForwardNativeInt32Into, embeddingBackwardNative, embeddingBackwardNativeInt32, embeddingBackwardSparseNative, embeddingAdamBackwardUpdateNative, embeddingSgdBackwardUpdateNative, embeddingAdagradBackwardUpdateNative, embeddingMomentumBackwardUpdateNative, embeddingNagBackwardUpdateNative, layerNormNativeInto, layerNormBackwardNativeInto, softmaxNativeInto, softmaxBackwardNativeInto, denseLinearBackwardNativeInto, projectLastTokenLogitsNativeInto, convolutionNativeInto, convBackwardInputNativeInto, applyAttentionMaskNative, multiHeadAttentionForwardNativeInto, multiHeadAttentionBackwardNativeInto, lstmForwardNativeInto, rnnForwardNativeInto, rnnBackwardNativeInto, gruForwardNativeInto, gruBackwardNativeInto, adaptiveMemoryRnnForwardNativeInto, adaptiveMemoryRnnBackwardNativeInto, adaptiveMemoryRnnBackwardFullNativeInto, clipGradientsNative } = nativeBinding

module.exports.dotProduct = dotProduct
module.exports.dotProductInto = dotProductInto
module.exports.dotProductIntoDims = dotProductIntoDims
module.exports.addMatricesInto = addMatricesInto
module.exports.subMatricesInto = subMatricesInto
module.exports.mulMatricesInto = mulMatricesInto
module.exports.divMatricesInto = divMatricesInto
module.exports.addInPlace = addInPlace
module.exports.subInPlace = subInPlace
module.exports.mulInPlace = mulInPlace
module.exports.addBiasNative = addBiasNative
module.exports.sumAxisNative = sumAxisNative
module.exports.reluNativeInto = reluNativeInto
module.exports.sigmoidNativeInto = sigmoidNativeInto
module.exports.tanhNativeInto = tanhNativeInto
module.exports.adamUpdateNative = adamUpdateNative
module.exports.adamSparseUpdateNative = adamSparseUpdateNative
module.exports.sgdUpdateNative = sgdUpdateNative
module.exports.sgdSparseUpdateNative = sgdSparseUpdateNative
module.exports.adagradUpdateNative = adagradUpdateNative
module.exports.adagradSparseUpdateNative = adagradSparseUpdateNative
module.exports.momentumUpdateNative = momentumUpdateNative
module.exports.momentumSparseUpdateNative = momentumSparseUpdateNative
module.exports.nagUpdateNative = nagUpdateNative
module.exports.nagSparseUpdateNative = nagSparseUpdateNative
module.exports.mseNative = mseNative
module.exports.maskedSparseSoftmaxCrossEntropyInto = maskedSparseSoftmaxCrossEntropyInto
module.exports.embeddingForwardNativeInto = embeddingForwardNativeInto
module.exports.embeddingForwardNativeInt32Into = embeddingForwardNativeInt32Into
module.exports.embeddingBackwardNative = embeddingBackwardNative
module.exports.embeddingBackwardNativeInt32 = embeddingBackwardNativeInt32
module.exports.embeddingBackwardSparseNative = embeddingBackwardSparseNative
module.exports.embeddingAdamBackwardUpdateNative = embeddingAdamBackwardUpdateNative
module.exports.embeddingSgdBackwardUpdateNative = embeddingSgdBackwardUpdateNative
module.exports.embeddingAdagradBackwardUpdateNative = embeddingAdagradBackwardUpdateNative
module.exports.embeddingMomentumBackwardUpdateNative = embeddingMomentumBackwardUpdateNative
module.exports.embeddingNagBackwardUpdateNative = embeddingNagBackwardUpdateNative
module.exports.layerNormNativeInto = layerNormNativeInto
module.exports.layerNormBackwardNativeInto = layerNormBackwardNativeInto
module.exports.softmaxNativeInto = softmaxNativeInto
module.exports.softmaxBackwardNativeInto = softmaxBackwardNativeInto
module.exports.denseLinearBackwardNativeInto = denseLinearBackwardNativeInto
module.exports.projectLastTokenLogitsNativeInto = projectLastTokenLogitsNativeInto
module.exports.convolutionNativeInto = convolutionNativeInto
module.exports.convBackwardInputNativeInto = convBackwardInputNativeInto
module.exports.applyAttentionMaskNative = applyAttentionMaskNative
module.exports.multiHeadAttentionForwardNativeInto = multiHeadAttentionForwardNativeInto
module.exports.multiHeadAttentionBackwardNativeInto = multiHeadAttentionBackwardNativeInto
module.exports.lstmForwardNativeInto = lstmForwardNativeInto
module.exports.rnnForwardNativeInto = rnnForwardNativeInto
module.exports.rnnBackwardNativeInto = rnnBackwardNativeInto
module.exports.gruForwardNativeInto = gruForwardNativeInto
module.exports.gruBackwardNativeInto = gruBackwardNativeInto
module.exports.adaptiveMemoryRnnForwardNativeInto = adaptiveMemoryRnnForwardNativeInto
module.exports.adaptiveMemoryRnnBackwardNativeInto = adaptiveMemoryRnnBackwardNativeInto
module.exports.adaptiveMemoryRnnBackwardFullNativeInto = adaptiveMemoryRnnBackwardFullNativeInto
module.exports.clipGradientsNative = clipGradientsNative
